name: Glen De Cauwsemaecker
url: http://glendc.com
description: Game Developer and Open Source Hacker

permalink: /:year/:month/:day/:title/
paginate: 5

highlighter: pygments
markdown:    kramdown

kramdown:
  input: 		 GFM
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']