name: Glen De Cauwsemaecker
url: http://glendc.com
description: Junior Programmer at Exient and Open Source Hacker

permalink: /:year/:month/:day/:title/
paginate: 5
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']